<script setup>
import { onUnmounted, ref, watch } from "vue";
import { NAlert, NButton, NCard, NEmpty, NInput, NList, NListItem, NSpace, NTag } from "naive-ui";
import { workflow } from "./api.js";
const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";

const props = defineProps({ workspaceId: { type: String, required: true }, workflowState: { type: Object, required: true }, taskState: { type: Object, default: null }, translationRequest: { type: Object, default: null } });
const emit = defineEmits(["candidate-selected", "segment-edited"]);
const bundle = ref(null); const activeId = ref(null); const candidates = ref([]); const text = ref(""); const workflowVersion = ref(null); const validation = ref(null); const quality = ref(null); const confirmedQualityFindings = ref(new Set()); const exportRecord = ref(null); const task = ref(null); const flow = ref(null); const error = ref(""); let timer = null;
const active = () => bundle.value?.segments.find((item) => item.segmentId === activeId.value) ?? null;
async function choose(item) { activeId.value = item.segmentId; text.value = item.text ?? ""; candidates.value = await workflow.listCandidates(props.workspaceId, props.workflowState.workflow.workflowId, item.segmentId); }
async function selectCandidate(candidate) { const item = active(); if (!item) return; try { await workflow.selectCandidate(props.workspaceId, props.workflowState.workflow.workflowId, item.segmentId, candidate.candidateId, item.version ?? null); emit("candidate-selected"); await load(); const refreshed = active(); if (refreshed) await choose(refreshed); } catch (cause) { error.value = cause.message; } }
async function load() { bundle.value = await workflow.getBundle(props.workspaceId, props.workflowState.workflow.workflowId); workflowVersion.value = bundle.value.workflow.version ?? null; if (!activeId.value && bundle.value.segments[0]) activeId.value = bundle.value.segments[0].segmentId; const item = active(); if (item) { text.value = item.text ?? ""; candidates.value = await workflow.listCandidates(props.workspaceId, props.workflowState.workflow.workflowId, item.segmentId); } }
async function edit() { const item = active(); if (!item) return; try { await workflow.editSegment(props.workspaceId, props.workflowState.workflow.workflowId, item.segmentId, item.version ?? null, text.value); emit("segment-edited"); await load(); } catch (cause) { error.value = cause.message; } }
async function validate() { try { validation.value = await workflow.validate(props.workspaceId, props.workflowState.workflow.workflowId); } catch (cause) { error.value = cause.message; } }
async function confirmWarning(item) { try { validation.value = await workflow.confirmWarning(props.workspaceId, props.workflowState.workflow.workflowId, validation.value.validationRunId, item.findingId); } catch (cause) { error.value = cause.message; } }
async function runQa() { try { quality.value = await workflow.runQuality(props.workspaceId, props.workflowState.workflow.workflowId); confirmedQualityFindings.value = new Set(); } catch (cause) { error.value = cause.message; } }
async function confirmQualityWarning(item) { try { quality.value = await workflow.confirmQualityWarning(props.workspaceId, props.workflowState.workflow.workflowId, quality.value.qualityRunId, item.findingId); confirmedQualityFindings.value = new Set([...confirmedQualityFindings.value, item.findingId]); } catch (cause) { error.value = cause.message; } }
async function review() { try { const result = await workflow.review(props.workspaceId, props.workflowState.workflow.workflowId, validation.value.validationRunId, workflowVersion.value, quality.value?.qualityRunId ?? null); workflowVersion.value = result.version ?? workflowVersion.value; } catch (cause) { error.value = cause.message; } }
async function approve() { try { const result = await workflow.approve(props.workspaceId, props.workflowState.workflow.workflowId, validation.value.validationRunId, workflowVersion.value, quality.value?.qualityRunId ?? null); workflowVersion.value = result.version ?? workflowVersion.value; } catch (cause) { error.value = cause.message; } }
async function exportFile(format) { try { exportRecord.value = await workflow.export(props.workspaceId, props.workflowState.workflow.workflowId, validation.value.validationRunId, format, quality.value?.qualityRunId ?? null); } catch (cause) { error.value = cause.message; } }
async function downloadFile() { if (!exportRecord.value?.exportId) return; const response = await fetch(`${API_BASE}/api/v1/workspaces/${encodeURIComponent(props.workspaceId)}/exports/${encodeURIComponent(exportRecord.value.exportId)}/download`, { credentials: "include" }); if (!response.ok) throw new Error("导出文件下载失败"); const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = exportRecord.value.filename; link.click(); URL.revokeObjectURL(link.href); }
async function runOffline() { try { const result = await workflow.runNextOffline(props.workspaceId); task.value = props.taskState?.taskId ? await workflow.getTask(props.workspaceId, props.taskState.taskId) : result; await load(); } catch (cause) { error.value = cause.message; } }
async function poll() { if (!task.value?.taskId) return; try { task.value = await workflow.getTask(props.workspaceId, task.value.taskId); if (["completed", "failed", "canceled", "unknown-outcome"].includes(task.value.state)) { clearInterval(timer); timer = null; await load(); } } catch (cause) { error.value = cause.message; } }
async function loadFlow() { try { flow.value = await workflow.getFlow(props.workspaceId, props.workflowState.workflow.workflowId); } catch (cause) { error.value = cause.message; } }
async function resolveFlow(action) { if (!flow.value) return; try { flow.value = await workflow.resolveFlow(props.workspaceId, props.workflowState.workflow.workflowId, flow.value.version, action, action === "retry" ? props.translationRequest : null); } catch (cause) { error.value = cause.message; } }
function startPoll() { if (timer) clearInterval(timer); timer = setInterval(poll, 1500); }
watch(() => props.workflowState.workflow.workflowId, () => { bundle.value = null; candidates.value = []; activeId.value = null; validation.value = null; load().catch((cause) => { error.value = cause.message; }); loadFlow(); }, { immediate: true });
watch(() => props.taskState, (value) => { task.value = value; if (value?.taskId && !timer) startPoll(); }, { immediate: true });
onUnmounted(() => { if (timer) clearInterval(timer); });
</script>

<template>
  <n-space vertical size="large">
    <n-alert v-if="error" type="error" :title="error" />
    <n-card title="离线执行验收"><n-space><n-button type="warning" :disabled="!taskState" @click="runOffline">运行下一项 Fake Provider 任务</n-button><n-tag v-if="task">{{ task.status ?? task.state ?? '等待执行' }}</n-tag></n-space></n-card>
    <n-card v-if="flow && (flow.flowState === 'paused' || flow.outcomeState !== 'none')" title="异常恢复"><n-space><n-tag type="error">{{ flow.pauseReason ?? flow.outcomeState }}</n-tag><n-button v-if="flow.outcomeState === 'unknown'" @click="resolveFlow('retry')">重试未完成任务</n-button><n-button secondary @click="resolveFlow('terminate')">终止流程</n-button></n-space></n-card>
    <n-card v-if="candidates.length" title="当前段候选"><n-list bordered><n-list-item v-for="candidate in candidates" :key="candidate.candidateId"><n-space justify="space-between"><span>{{ candidate.text }}</span><n-button size="small" type="primary" @click="selectCandidate(candidate)">采用候选</n-button></n-space></n-list-item></n-list></n-card>
    <n-card title="分段翻译工作台"><n-button secondary @click="load">刷新分段</n-button><n-list v-if="bundle?.segments?.length" bordered><n-list-item v-for="item in bundle.segments" :key="item.segmentId"><n-button text @click="choose(item)">#{{ item.ordinal + 1 }} {{ item.sourceText.slice(0, 80) }}</n-button><n-tag style="margin-left: 10px">{{ item.text ? '已有译文' : '待翻译' }}</n-tag></n-list-item></n-list><template v-if="active()"><n-alert type="info" :title="active().sourceText" /><n-input v-model:value="text" type="textarea" :autosize="{ minRows: 4, maxRows: 10 }" /><n-button type="primary" @click="edit">保存编辑</n-button></template><n-empty v-else description="没有可编辑的分段" /></n-card>
    <n-card title="Validator、质量 QA、审核与导出"><n-space><n-button type="primary" @click="validate">运行确定性 Validator</n-button><n-button secondary :disabled="!validation" @click="runQa">运行全文 QA</n-button></n-space><n-list v-if="validation?.findings?.length" bordered><n-list-item v-for="item in validation.findings" :key="item.findingId">{{ item.severity }} · {{ item.code }}<n-button v-if="item.severity === 'warning'" size="small" @click="confirmWarning(item)">确认警告</n-button></n-list-item></n-list><n-alert v-if="quality && !quality.findings.length" type="success" title="QA 未发现问题" /><n-list v-if="quality?.findings?.length" bordered><n-list-item v-for="item in quality.findings" :key="item.findingId"><n-space justify="space-between" style="width:100%"><span>{{ item.severity }} · {{ item.ruleId }}</span><n-tag v-if="confirmedQualityFindings.has(item.findingId)" type="success">已确认</n-tag><n-button v-else-if="item.severity === 'warning'" size="small" @click="confirmQualityWarning(item)">确认 QA 警告</n-button></n-space></n-list-item></n-list><n-space v-if="validation"><n-button @click="review">人工审核完成</n-button><n-button type="success" @click="approve">批准导出</n-button><n-button @click="exportFile('markdown')">导出 Markdown</n-button><n-button @click="exportFile('html')">导出 HTML</n-button><n-button @click="exportFile('text')">导出纯文本</n-button><n-button @click="exportFile('canonical')">导出 Canonical</n-button></n-space><n-space v-if="exportRecord"><n-alert type="success" :title="`导出完成：${exportRecord.filename}`" /><n-button type="primary" @click="downloadFile">下载文件</n-button></n-space></n-card>
  </n-space>
</template>
